// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import TomSelect from "@umts/stimulus/tom-select"
import Clipboard from "@umts/stimulus/clipboard"
import Popover from "@umts/stimulus/popover"
import Template from "@umts/stimulus/template"
import Remove from "@umts/stimulus/remove"

import AssignmentCalendarController from "./assignment_calendar_controller"
application.register("assignment-calendar", AssignmentCalendarController)

application.register("clipboard", Clipboard)

import LoginController from "./login_controller"
application.register("login", LoginController)

application.register("popover", Popover)

application.register("remove", Remove)

application.register("template", Template)

application.register("tom-select", TomSelect)
