// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AssignmentCalendarController from "./assignment_calendar_controller"
application.register("assignment-calendar", AssignmentCalendarController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import LoginController from "./login_controller"
application.register("login", LoginController)
