plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - 'bin/brakeman'
    - 'bin/bundle'
    - 'bin/haml-lint'
    - 'bin/rspec'
    - 'bin/rubocop'
    - 'bin/thrust'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
  NewCops: enable

Metrics/AbcSize:
  CountRepeatedAttributes: false

Metrics/BlockLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false
