plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - config/environments/**/*
    - db/schema.rb
    - db/migrate/**/*
    - vendor/**/*
  NewCops: enable

Metrics/AbcSize:
  CountRepeatedAttributes: false

Metrics/BlockLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false
