# <% def user_for(host) = Net::SSH::Config.for(host).fetch(:user, ENV.fetch('USER', nil)) %>

service: screaming_dinosaur
image: umts/screaming-dinosaur
registry:
  server: ghcr.io
  username: not_needed
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
  provenance: false
  sbom: false
labels:
  org.opencontainers.image.source: "https://github.com/umts/screaming-dinosaur"
servers:
  web:
    - afs-umts-web4.admin.umass.edu
proxy:
  ssl: true
  host: umts-oncall.admin.umass.edu
env:
  clear:
    TZ: America/New_York
  secret:
    - RAILS_MASTER_KEY
ssh:
  user: <%= user_for 'afs-umts-web4.admin.umass.edu' %>
volumes:
  - "screaming_dinosaur_log:/rails/log"
  - "screaming_dinosaur_storage:/rails/storage"
