name: pull_request
permissions:
  contents: read
on:
  pull_request:
jobs:
  integrate:
    uses: umts/shared-workflows/.github/workflows/integrate-rails.yml@45a657bbe392751472f14fd638845093af4509cb # main
