name: pull_request
permissions:
  contents: read
on:
  pull_request:
jobs:
  integrate:
    uses: umts/shared-workflows/.github/workflows/integrate-rails.yml@7ae11bc6464f7030bff7f930dc9b3e7a22f6bd68 # main
